Add pull request template and move CONTRIBUTE.md to .github
percona/percona-toolkit pull request #133
Opened 2016-09-13 12:53 UTC by dveeden

Add a template for pull requests

This is BSD licensed.

2016-11-16 20:36 UTC, percona-csalguero commented
could you fix the conflicts please?

2017-01-12 15:42 UTC, percona-csalguero commented
@dveeden Sorry for the delay. Could you fix the conflicts to merge this commit?
Thanks

2017-01-15 22:11 UTC, dveeden commented
@percona-csalguero done

2022-09-15 10:01 UTC, percona-csalguero requested changes

2022-09-15 10:01 UTC, percona-csalguero commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] The contributed code is licensed under BSD
```suggestion
- [ ] The contributed code is licensed under GPL v2.0
```
https://github.com/percona/percona-toolkit/blob/3.x/COPYING

2022-09-28 17:29 UTC, svetasmirnova requested changes
We updated CONTRIBUTE.md and CONTRIBUTING.md in the current main branch 3.x. Renaming CONTRIBUTE.md to CONTRIBUTING.md wipes out these changes. Could you please remove this file from this PR?

2022-09-28 20:24 UTC, dveeden commented
@svetasmirnova done. PTAL.

2022-12-28 00:26 UTC, percona-csalguero approved these changes

2023-01-27 12:27 UTC, svetasmirnova approved these changes

2023-01-27 12:27 UTC, merged