Allow a certain percentage of slaves to lag
percona/percona-toolkit pull request #154
Opened 2016-12-07 17:12 UTC by DrMurx

This PR allows `pt-table-checksum` or `pt-online-schema-change` to continue even if a certain percentage of slave servers is lagging behind.

It addresses setups where, for example, single slaves are continuously taken out of the cluster for `OPTIMIZE TABLE` or other administrative measures.

This is still a bit of WIP but I wanted to make this feature already available to others in this early stage.

2020-05-15 18:49 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=154) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=154) before we can accept your contribution.<br/><hr/>**Jan Kunzmann** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=154) it.</sub>

2020-05-26 00:41 UTC, DrMurx commented
I do not work for this company anymore and have neither access to their github repositories nor to the email address the commit was done with.

2022-09-14 23:42 UTC, svetasmirnova requested changes
Thank you for your contribution.

Could you please sign CLA and add a test case? You will find examples in the directory t.

2023-12-08 12:34 UTC, svetasmirnova commented
Rejecting because CLA is not signed. If you find a way to sign CLA feel free to reopen this PR.

2023-12-08 12:34 UTC, closed without merging