added support for operf if present, and if CMD_OPCONTROL is not set
percona/percona-toolkit pull request #160
Opened 2017-01-24 22:28 UTC by fipar

This branch updates --collect-oprofile so that it works with oprofile >= 1.0.0 (in which opcontrol is deprecated, as noted by Valeriy here: http://mysqlentomologist.blogspot.com/2017/01/oprofile-basics-for-mysql-profiling.html).

2017-02-08 03:07 UTC, vadimtk commented
Fernando,

For all contributions we ask to sign our CLA.
Please review it here
To get started, <a href="https://www.clahub.com/agreements/percona/percona-toolkit">sign the Contributor License Agreement</a>.

2017-02-08 15:28 UTC, fipar commented
Vadim, 

I have signed the CLA. 
Regards,

2022-09-14 23:39 UTC, svetasmirnova requested changes
Thank you for your contribution. Could you please add a test case. You can find examples in the directory t.

2024-01-26 15:15 UTC, svetasmirnova approved these changes

2024-01-29 05:03 UTC, saikumar-vs approved these changes

2024-01-29 09:56 UTC, merged