pt-pmp improvements
percona/percona-toolkit pull request #183
Opened 2017-03-15 16:45 UTC by alexey2k

Added:
- pt-eustack-resolver tool for offline symbol resoving of eu-stack trackes

Extended pt-pmp tool:

    - added possibility to collect stack traces with:
               eu-pstack(elfutils)
               pt-eustack-resolver(elfutils+offline symbol resoving tool)
               quickstack(https://github.com/yoshinorim/quickstack)
      New option: -d <default:gdb|eu|pteu|qs>

    - added possibility to filter out output that it will include only specific tids
      New option: -t <tid>[<tid>,<tid>,...]

    - added posibility to use "--readnever" option for gdb if available
    - various minor fixes

2017-05-24 18:26 UTC, percona-csalguero commented
Is it possible to add tests?

2020-05-15 18:48 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=183) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=183) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=183) it.</sub>

2022-12-01 12:47 UTC, svetasmirnova requested changes
I do not see changes for pt-pmp. Did you mean version, available at https://github.com/Percona-Lab/pt-pmp ?

2024-01-16 23:29 UTC, svetasmirnova commented
We will perform this port as part of https://github.com/percona/percona-toolkit/pull/754

2024-01-16 23:29 UTC, closed without merging