Print database name when logging pt-kill output to file
percona/percona-toolkit pull request #405
Opened 2019-07-02 19:36 UTC by dreamydb

With multiple dbs in a single instance, its helpful to have pt-kill print the database name to the log file. 

With the suggested code change, an example output would show db name in the fourth column as shown below:

```
pt-kill --user=<user> --password=<password> --socket=<socket> --busy-time=20 --interval=15 --print --match-command=Query --daemonize --log <logfile>

# 2019-05-30T10:30:42 KILL 23063482 skyzer (Query 41 sec) SELECT domain FROM domains_data
# 2019-05-30T10:46:57 KILL 23080285 ddb2 (Query 20 sec) SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes'
# 2019-05-30T10:47:12 KILL 23080285 ddb2 (Query 35 sec) SELECT option_name, option_value FROM wp_options WHERE autoload = 'yes'
# 2019-05-30T23:18:30 KILL 24551301 skyzer (Query 27 sec) DELETE FROM domains_data WHERE completed IS NULL
# 2019-05-30T23:22:00 KILL 24559692 skyzer (Query 25 sec) optimize table domains_data
# 2019-05-30T23:23:09 KILL 24559702 alph_co (Query 27 sec) UPDATE fus_settings SET settings_value=settings_value+1 WHERE settings_name='counter'
```

2019-07-02 19:37 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=405) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=405) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=405) it.</sub>

2022-09-14 12:37 UTC, svetasmirnova requested changes
Thank you for your contribution.

Your code fails if the default database is not set ($query->{db} is undef), it does not add additional positional formatting for the new element, and breaks tests in the t/pt-kill directory. Please fix these issues.

2023-12-24 02:30 UTC, midla301 approved these changes

2026-06-11 22:15 UTC, svetasmirnova approved these changes

2026-06-12 05:29 UTC, saikumar-vs approved these changes

2026-06-12 05:49 UTC, EvgeniyPatlan approved these changes

2026-06-12 12:39 UTC, merged