Improved handling of enum columns in pk
percona/percona-toolkit pull request #412
Opened 2019-09-01 18:46 UTC by tgriffitts-vs

https://jira.percona.com/browse/PT-1591
https://jira.percona.com/browse/PT-1572

These tickets describe a problem with the underlying NibbleIterator in the way it treats enum values in keys.  In short, e.g., c enum('a', 'z', 'b'), the issue is that MySQL ORDER BY clause orders by enum index value ('a', 'z', 'b') and the NibbleIterator specifies boundaries as strings,e.g., WHERE c <= 'b'. In MySQL, this returns only 'a' because 'a' is alphanumerically <= 'b', but the ORDER BY returns 'z' rows before 'b' rows and they will be missed in the nibble. The solution provided in the tickets quoted above changes the ORDER BY clause to force conversion of the enum to a string and forces creation of a new sort order index each nibble.  On large tables, this is unreasonably slow (it would have taken 32 years to convert our table of 1.7billion rows).

The solution in this patch to assure all enum columns are referenced by their enum index value.  In MySQL, this is done by casting an enum column to an UNSIGNED.  This causes the ORDER BY and comparisons to sort and also compare all values using the enum index value and never using a string representation of the name values for the enum.  This enables the natural order of the key to be used, removing the need to create a new sort index for each nibble.  In short, this reduces the time for a schema update of our tables from years to hours, and I hope is a more desired fix for the issue recorded in the tickets mentioned above.

2019-09-01 18:46 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=412) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=412) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=412) it.</sub>

2022-09-14 12:13 UTC, svetasmirnova requested changes
Thank you for your contribution.

You modified the auto-generated code. It will be removed once we run the update-modules utility. Please put your changes into the TableNibbler package instead.

2022-09-20 11:23 UTC, percona-csalguero commented
Hi, 
As Sveta mentioned, these changes should be applied on `NibbleIterator.pm` and then they must be applied to all programs using that package with something like:
```
for t in bin/*; do util/update-modules $t NibbleIterator; done
```

2022-09-20 11:23 UTC, percona-csalguero commented
Please also: 
1. Fix merge conflicts
2. This should be merged into the `3.x` branch, not in `3.0`

2023-02-22 14:04 UTC, percona-csalguero commented
@svetasmirnova Since this issue seems to be abandoned, can we close it?

2023-02-22 16:37 UTC, svetasmirnova commented
@percona-csalguero let me review if changes are safe first. We can probably adjust the patch ourselves if it can help us to improve speed of handling ENUM indexes without loosing data.

2024-12-31 15:35 UTC, closed without merging

2024-12-31 15:35 UTC, svetasmirnova commented
Looks like changes, similar to your PR were implemented in https://github.com/percona/percona-toolkit/commit/e58b9fbea8e82ccd996a222256193e07e3d68340 So closing this PR.