Added option to log queries to database
percona/percona-toolkit pull request #424
Opened 2019-10-16 13:27 UTC by sjalilund

Added option to log potential victims to the database specified in the dsn that is specified for logging killed queries.
This to get a central place to store the logged potential victims, instead of just locally on the file system of the target database.

2019-10-16 13:27 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=424) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=424) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=424) it.</sub>

2022-09-14 10:26 UTC, svetasmirnova requested changes
Thank you for your contribution.

Please add a test case. You will find examples in the directory t.

2025-03-13 20:42 UTC, svetasmirnova commented on bin/pt-kill
> +                     eval_error => $EVAL_ERROR,
EVAL_ERROR makes sense only after pt-kill tried to kill the query.

2025-03-13 20:43 UTC, svetasmirnova commented on bin/pt-kill
> +               if ( $log ) {
What if someone specifies option --logdb and not --log?

2025-03-13 20:44 UTC, svetasmirnova commented on bin/pt-kill
> +=item --logdb
Not very intuitive name for the option.

2026-06-11 22:34 UTC, svetasmirnova commented
There is such an option already: --log-dsn

2026-06-11 22:34 UTC, closed without merging