PT-1776: Adding in slave-user and slave-password for dsn table based …
percona/percona-toolkit pull request #425
Opened 2019-10-25 15:18 UTC by mbenshoof

…recursion

2019-10-25 15:18 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=425) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=425) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=425) it.</sub>

2022-09-14 10:17 UTC, svetasmirnova requested changes
Thank you for your contribution.

You modified the auto-generated code. It will be removed once we run the update-modules utility. Please put your changes into the MasterSlave package.

2023-11-06 15:21 UTC, svetasmirnova commented
Another issue with this proposal is that it modifies DSN table entries without checking if they have user and password defined. This could cause issues when users have, say, 10 replicas with the same user/password pairs and two with different ones.

We also need a test case to accept this PR.

2023-11-06 15:46 UTC, svetasmirnova commented
There is also similar PR at https://github.com/percona/percona-toolkit/pull/381

2023-12-20 16:43 UTC, mbenshoof commented
@svetasmirnova - Modified the logic to check for user/pass specified in DSN string.  Only sets the CLI passed options if they are not set in the DSN table.

For the test case, I've been using dbdeployer for a quick primary/replica environment and setting different variations of DSN string in the table (with both user/pass, with only one, with neither) to validate it doesn't overwrite, but sets if missing

2023-12-29 15:43 UTC, svetasmirnova commented
@mbenshoof 

Thank you for the changes; I will review them in the new year.

> For the test case, I've been using dbdeployer for a quick primary/replica environment and setting different variations of the DSN string in the table (with both user/pass, with only one, with neither) to validate it doesn't overwrite, but sets if missing

We need automatic test cases to run them at each release and ensure your changes are not overwritten by another contribution. We use a solution similar to MySQL Sandbox and dbdeployer for automatic test cases. Please check directory t and CONTRIBUTING.md.

2026-06-25 16:09 UTC, svetasmirnova commented on t/pt-table-checksum/pt-2052.t
> +}
Added manually

2026-06-25 16:10 UTC, svetasmirnova commented on lib/MasterSlave.pm
> +            };
Added manually

2026-06-25 21:14 UTC, svetasmirnova approved these changes

2026-06-29 11:41 UTC, EvgeniyPatlan approved these changes

2026-06-29 13:56 UTC, merged