Query information schema for list of tables
percona/percona-toolkit pull request #435
Opened 2020-01-25 06:13 UTC by ernesto-alikarami

Modified line 7810 of pt-table-checksum to fetch tables from information schema rather than the actual catalog.

Also added aliases to make sure returned value would be evaluated in the same way.

This will make execution of the script faster as previous query is often slow, depending on the number of tables and usage of the catalog

2020-01-25 06:13 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=435) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=435) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=435) it.</sub>

2022-09-13 21:59 UTC, svetasmirnova requested changes
Thank you for your contribution.
You made changes in the auto-generated code that will be replaced once we run the update-modules utility. Please port your changes into the SchemaIterator package instead.

2023-02-22 14:09 UTC, percona-csalguero commented
@svetasmirnova This one seems to be abandoned and it doesn't have tests.
Can we close it?

2023-02-22 16:20 UTC, svetasmirnova commented
@percona-csalguero Agree. Also, SHOW TABLES is mapped to the Information Schema query, so performance should be the same in both cases.

2023-02-22 16:20 UTC, closed without merging