Change jemalloc detection
percona/percona-toolkit pull request #437
Opened 2020-03-06 10:28 UTC by fmbiete

Simplify jemalloc detection for cases where is not in standard locations or we have multiple versions available in the system. 
pmap is always the source of truth for what libraries are being used.

2020-03-06 10:28 UTC, it-percona commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=437) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=437) it.</sub>

2020-03-06 10:30 UTC, fmbiete commented
This would also solve: PT-1628

2022-09-13 21:55 UTC, svetasmirnova requested changes
You made changes in the auto-generated code that will be overridden by the update-modules utility. Please, move your change into the report_mysql_info package. 
Please also add a test case. You will find examples in the t directory.

2023-11-06 14:45 UTC, svetasmirnova commented
We cannot repeat PT-1628 anymore. This contribution does not test cases, demonstrating the issue and its resolution, so rejecting it. If you can update it to the current version, put the fix into the proper place, and add test cases, feel free to re-open it.

2023-11-06 14:45 UTC, closed without merging