Support adding explain output for slow query in JSON report as well
percona/percona-toolkit pull request #471
Opened 2020-11-05 08:50 UTC by perfectayush

I am generating JSON reports from slow logs and consuming them for a visual dashboard in elasticsearch.
I find it useful to add the EXPLAIN output in the JSON reports as well.

2020-11-05 08:50 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=471) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=471) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=471) it.</sub>

2022-09-13 21:45 UTC, svetasmirnova requested changes
You changed the auto-generated part of the bin/pt-query-digest code. These changes will be overwritten once we rebuild the tool using the update-modules utility. Please make changes in the package JSONReportFormatter instead.

Please, also add the test case. You will find examples in the directory t.

2023-11-06 14:23 UTC, svetasmirnova approved these changes

2023-11-12 19:17 UTC, EvgeniyPatlan approved these changes

2023-11-12 20:28 UTC, merged