Fix test PT-1966
percona/percona-toolkit pull request #493
Opened 2021-06-08 04:56 UTC by yoku0825

- [\[PT\-1966\] t/pt\-online\-schema\-change/no\_drop\_no\_swap\.t is broken \- Percona JIRA](https://jira.percona.com/browse/PT-1966)

no_drop_no_swap.t  dies by `Error altering new table `pt_osc`.`_t_new`: DBD::mysql::db do failed: Duplicate column name 'd' [for Statement "ALTER TABLE `pt_osc`.`_t_new` ADD COLUMN d INT"]` .

This pull-request changes adding column name to avoid duplicate column name.

2021-06-08 04:56 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=493) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=493) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=493) it.</sub>

2021-06-08 12:04 UTC, percona-csalguero requested changes
Hi, thanks for the contribution.
Could you please change the test removing the `eval` and checking the exit code like we do  [here](https://github.com/percona/percona-toolkit/blob/3.x/t/pt-online-schema-change/basics.t#L56-L59) ?
```
($output, $exit) = full_output(
   sub { pt_online_schema_change::main(@args, "$dsn,D=pt_osc,t=t",
      '--alter', 'drop column id') }
);
```

2021-06-08 13:19 UTC, yoku0825 commented
@percona-csalguero Hi! Thank you for your suggestion, that's a good way to catch an error!
I fixied and push it. thanks!

2021-06-09 19:08 UTC, percona-csalguero approved these changes

2021-06-09 19:12 UTC, percona-csalguero commented
One more thing, please.
Could you update the changelog and mention youself as the contributor? (if you want to)
Thanks

2021-06-10 07:07 UTC, yoku0825 commented
I added `Changelog`, thank you.

2021-06-10 12:01 UTC, percona-csalguero commented
Hi, There was another pull request and now the Changelog has a conflict. 
Could you please fix it, leaving both changes 1965 and 1966?
Once it is fixed, I'll merge it.
Thanks

2021-06-11 03:56 UTC, yoku0825 commented
I fixed the conflict. thanks!

2021-06-17 13:28 UTC, merged