versions update
percona/percona-toolkit pull request #505
Opened 2021-08-03 09:39 UTC by rnovikovP

according to https://www.percona.com/services/policies/percona-software-support-lifecycle#pt

2021-08-03 09:46 UTC, denisok commented
OK, and do we have those packages ?

2021-08-03 12:17 UTC, percona-csalguero approved these changes

2021-08-09 12:51 UTC, denisok requested changes

2021-08-09 12:51 UTC, denisok commented on docs/installation.rst
> +* Debian 8 ("Jessie")
https://www.percona.com/downloads/percona-toolkit/LATEST/  there is no Debian 8 choice...

2021-08-09 16:34 UTC, denisok approved these changes

2021-08-10 10:50 UTC, merged