added new hook before_die
percona/percona-toolkit pull request #509
Opened 2021-08-17 15:45 UTC by migliozziilaria

before die, the script calls the new hook (before_die) in oder to execute extra user's operations.

Alternatively, you could call the before_exit hook.

2021-08-17 15:45 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=509) it.</sub>

2022-04-07 13:09 UTC, ynuyasha commented
Hi @percona-csalguero someone can take care of this PR?

2022-04-07 14:37 UTC, percona-csalguero commented
Hi, thanks for the contribution.
Would it be possible to write a test? There are examples in the `t` directory.

Thanks

2022-09-13 21:04 UTC, svetasmirnova requested changes
Please add a test case as was suggested by @percona-csalguero

2023-11-03 16:43 UTC, svetasmirnova commented on bin/pt-online-schema-change
> +my $plugin;
Why did you make this variable global? It is enough to have it defined inside the main function.

2023-11-03 16:50 UTC, svetasmirnova commented on bin/pt-online-schema-change
> +my $plugin;
Gotcha: to use it in the sub _die.

2023-11-03 21:49 UTC, svetasmirnova approved these changes

2023-11-06 14:54 UTC, EvgeniyPatlan approved these changes

2023-11-06 15:22 UTC, merged