fix Cannot find encoding "utf8mb4"
percona/percona-toolkit pull request #538
Opened 2022-04-03 10:28 UTC by slowtech

Here is a test case.

`
mysql> select @@version;
+------------+
| @@version  |
+------------+
| 5.7.36-log |
+------------+
1 row in set (0.00 sec)

mysql> show create table sbtest.t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL,
  `c1` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> show create table sbtest.t2\G
*************************** 1. row ***************************
       Table: t2
Create Table: CREATE TABLE `t2` (
  `id` int(11) NOT NULL,
  `c1` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> select * from sbtest.t1;
+----+--------------+
| id | c1           |
+----+--------------+
|  1 | slowtech😊     |
+----+--------------+
1 row in set (0.00 sec)
`
then we archive data from t1 to t2.

./pt-archiver --source h=127.0.0.1,P=3307,u=root,p=123456,D=sbtest,t=t1 --dest h=127.0.0.1,P=3307,u=root,p=123456,D=sbtest,t=t2 --bulk-insert --limit 10 --where '1=1' --bulk-delete --charset utf8mb4
Cannot find encoding "utf8mb4" at ./pt-archiver line 6712.

The essential reason is that the file encoding cann't be ut8mb4.

2022-04-03 10:28 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=538) before we can accept your contribution.<br/><hr/>**ivictor@foxmail.com** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=538) it.</sub>

2022-09-12 13:48 UTC, svetasmirnova requested changes
Thank you for your contribution!

For us to accept it, you need to sign CLA. Please do it.

Please, also add a test case for your change.

2022-09-23 12:27 UTC, percona-csalguero commented
I am not sure if changing the variable value to `utf8` will work. 
It might work for this particular case but we need to add several test cases, with tables using `utf8` and `utf8mb4` and with MySQL 5.7 & MySQL 8.0+

2022-09-28 00:01 UTC, svetasmirnova commented
> I am not sure if changing the variable value to `utf8` will work. It might work for this particular case but we need to add several test cases, with tables using `utf8` and `utf8mb4` and with MySQL 5.7 & MySQL 8.0+

That character set in the tool's code is for the Perl module, not for MySQL. Perl understands such MySQL encodings as cp1251 but does not understand utf8mb4.

2022-09-28 11:47 UTC, percona-csalguero commented
> > I am not sure if changing the variable value to `utf8` will work. It might work for this particular case but we need to add several test cases, with tables using `utf8` and `utf8mb4` and with MySQL 5.7 & MySQL 8.0+
> 
> That character set in the tool's code is for the Perl module, not for MySQL. Perl understands such MySQL encodings as cp1251 but does not understand utf8mb4.

Exactly. That's why I am not sure about changing the value for the `charset` variable that might be used globally will work.
We should add several test cases to ensure we are not affecting the DB connection charset.

2022-09-28 17:35 UTC, svetasmirnova commented
@percona-csalguero , you are correct. It is safer to use the different variable name for the binmode code, because variable $charset is used in many other places.

@slowtech , please, adjust your PR

2023-11-06 20:30 UTC, svetasmirnova commented
Fixed the same issue differently, by https://github.com/percona/percona-toolkit/pull/705

2023-11-06 20:30 UTC, closed without merging