PT-2084 show slave status
percona/percona-toolkit pull request #545
Opened 2022-07-27 03:10 UTC by guriandoro

PT-2084 -- Re-adding show slave status outputs to pt-stalk.

Work done on PT-80 removed these outputs for versions 5.7+, which is not desirable (and the P_S outputs we get in them are not enough to get all data we have in slave status outputs).

Additionally, I'm adding a conditional for checking versions 8.1+ if they decide to remove the "slave" syntax:

https://dev.mysql.com/doc/refman/8.0/en/show-replica-status.html
>From MySQL 8.0.22, use [SHOW REPLICA STATUS](https://dev.mysql.com/doc/refman/8.0/en/show-replica-status.html) in place of [SHOW SLAVE STATUS](https://dev.mysql.com/doc/refman/8.0/en/show-slave-status.html), which is deprecated from that release.

Since ${mysql_version} is not using patch number, we can't compare on 8.0.22, but using 8.1 is a good workaround that will make this patch work in future releases too.

Let me know what you think.

2022-08-01 11:58 UTC, svetasmirnova requested changes
SHOW REPLICA STATUS exists since 8.0.22, therefore check regarding 8.1 is wrong.
Also, there is no 8.1 version yet. Did you mean 8.0.1?
Also, please, add a test case for the change as described at https://github.com/percona/percona-toolkit/blob/3.x/CONTRIBUTE.md#setting-up-the-development-environment-and-testing

2022-08-01 15:54 UTC, guriandoro commented
Sveta,

Let me comment inline.

>SHOW REPLICA STATUS exists since 8.0.22, therefore check regarding 8.1 is wrong.

The ${mysql_version} variable pt-stalk uses to check versions only has major.minor values, so it's impossible for us to check if version is greater, equal or less than 8.0.22 in particular. We have to work with 5.7, 8.0, etc.

>Also, there is no 8.1 version yet. Did you mean 8.0.1?

I know there is no 8.1 yet. That part was being preemptive of future changes, in which since it's deprecated in 8.0.22, it will most likely be removed in 8.1+ in the future. This is to avoid the tool breaking in the future.

>Also, please, add a test case for the change 

Ok.

Thanks!

2022-09-12 12:38 UTC, svetasmirnova commented
OK, that makes sense regarding 8.1 Awaiting tests.

2023-01-05 22:09 UTC, guriandoro commented
Sveta,

New test case created as t/pt-stalk/pt-stalk-replication.t.
Please review it and let me know what you think.

2023-01-05 22:56 UTC, svetasmirnova commented on t/pt-stalk/pt-stalk-replication.t
> +#ok($sb->ok(), "Sandbox servers") or BAIL_OUT(__FILE__ . " broke the sandbox");
```suggestion
ok($sb->ok(), "Sandbox servers") or BAIL_OUT(__FILE__ . " broke the sandbox");
```
We need to check if we left the sandbox in a consistent state.

2023-01-05 22:57 UTC, svetasmirnova approved these changes
We may need to fix test case in the future to check for REPLICA syntax as well.

2023-02-02 13:18 UTC, percona-csalguero approved these changes

2023-02-02 14:08 UTC, merged