v3.4.0 release notes
percona/percona-toolkit pull request #548
Opened 2022-08-17 10:16 UTC by sleto-it

2022-08-17 10:16 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=548) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=548) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=548) it.</sub>

2022-08-18 09:23 UTC, nastena1606 approved these changes
LGTM

2022-08-18 10:26 UTC, rasika-chivate requested changes

2022-08-18 10:26 UTC, rasika-chivate commented on docs/release_notes.rst
> +* :jirabug:`PT-1965`: pt-stalk --mysql-only doesn't collect mysqladmin output (Thanks Sergey Kuzmichev)
```suggestion
* :jirabug:`PT-1965`: pt-stalk --mysql-only doesn't collect mysqladmin output
```

2022-08-18 10:26 UTC, rasika-chivate commented on docs/release_notes.rst
> +* :jirabug:`PT-1966`: Test no_drop_no_swap for the pt-online-schema-change is broken (Thanks Tsubasa Tanaka)
```suggestion
* :jirabug:`PT-1966`: Test no_drop_no_swap for the pt-online-schema-change is broken
```

2022-08-18 10:26 UTC, rasika-chivate commented on docs/release_notes.rst
> +* :jirabug:`PT-1953`: pt-summary typo: Memory mamagement.
```suggestion
* :jirabug:`PT-1953`: pt-summary typo: Memory management.
```

2022-08-18 10:27 UTC, rasika-chivate approved these changes

2022-08-18 10:32 UTC, nastena1606 approved these changes
LGTM

2022-08-18 10:33 UTC, merged