Updated makefile for builds
percona/percona-toolkit pull request #556
Opened 2022-10-20 16:42 UTC by percona-csalguero

Updated Makefile to avoid need of Git.

In our build environment, we don't have Git installed and the packages are being built from the .tar.gz file downloaded from the repo.
Because of that, we cannot use git command to get the tags nor commit sha. The new makefile creates a file that holds the version and commit SHA used to build the go binaries.

2022-10-21 12:31 UTC, EvgeniyPatlan approved these changes

2022-12-01 12:05 UTC, svetasmirnova approved these changes

2022-12-01 12:11 UTC, svetasmirnova requested changes
@percona-csalguero please check version of the text package and also license issues

2022-12-01 12:11 UTC, svetasmirnova commented on src/go/tools/go.mod
> +	golang.org/x/text v0.3.7 // indirect
```suggestion
	golang.org/x/text v0.3.8 // indirect
```

2022-12-05 14:57 UTC, closed without merging