PT-2139 - CVEs in golang binaries
percona/percona-toolkit pull request #569
Opened 2022-12-28 22:37 UTC by svetasmirnova

Updated version for golang.org/x/text to 0.3.8
golang.org/x/net is already in the newest version v0.0.0-20221114191408-850992195362

2022-12-29 11:44 UTC, tplavcic requested changes
Trivy scanner says that `net` module needs to be changed also (check the Fixed version column):
```
┌───────────────────┬────────────────┬──────────┬───────────────────────────────────┬───────────────────────────────────┬──────────────────────────────────────────────────────────────┐
│      Library      │ Vulnerability  │ Severity │         Installed Version         │           Fixed Version           │                            Title                             │
├───────────────────┼────────────────┼──────────┼───────────────────────────────────┼───────────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/net  │ CVE-2022-27664 │ HIGH     │ 0.0.0-20220403103023-749bd193bc2b │ 0.0.0-20220906165146-f3363e06e74c │ golang: net/http: handle server errors after sending GOAWAY  │
│                   │                │          │                                   │                                   │ https://avd.aquasec.com/nvd/cve-2022-27664                   │
│                   ├────────────────┼──────────┤                                   ├───────────────────────────────────┼──────────────────────────────────────────────────────────────┤
│                   │ CVE-2022-41717 │ MEDIUM   │                                   │ 0.4.0                             │ An attacker can cause excessive memory growth in a Go server │
│                   │                │          │                                   │                                   │ accepting...                                                 │
│                   │                │          │                                   │                                   │ https://avd.aquasec.com/nvd/cve-2022-41717                   │
├───────────────────┼────────────────┼──────────┼───────────────────────────────────┼───────────────────────────────────┼──────────────────────────────────────────────────────────────┤
│ golang.org/x/text │ CVE-2022-32149 │ HIGH     │ 0.3.7                             │ 0.3.8                             │ golang: golang.org/x/text/language: ParseAcceptLanguage      │
│                   │                │          │                                   │                                   │ takes a long time to parse complex tags                      │
│                   │                │          │                                   │                                   │ https://avd.aquasec.com/nvd/cve-2022-32149                   │
└───────────────────┴────────────────┴──────────┴───────────────────────────────────┴───────────────────────────────────┴──────────────────────────────────────────────────────────────┘
```

2022-12-29 15:30 UTC, svetasmirnova commented
@tplavcic Updated, see new commit.

2022-12-29 17:34 UTC, tplavcic approved these changes

2022-12-29 17:36 UTC, tplavcic commented
To me this looks ok now, although not sure if you need to run `go mod tidy` also, because when I run it on this branch I get one change in go.sum file (I'm no golang expert so not sure if it is needed to commit this or not).
@cfsalguero please check it too.

2023-01-02 12:27 UTC, percona-csalguero commented
> To me this looks ok now, although not sure if you need to run `go mod tidy` also, because when I run it on this branch I get one change in go.sum file (I'm no golang expert so not sure if it is needed to commit this or not). @cfsalguero please check it too.

I ran `go mod tidy` and pushed the commit

2023-01-02 17:31 UTC, svetasmirnova reviewed
Looks good to me

2023-01-03 14:25 UTC, percona-csalguero approved these changes

2023-01-03 17:12 UTC, merged