Only rollback destination if it's defined
percona/percona-toolkit pull request #604
Opened 2023-03-09 14:26 UTC by mikrobi

This change addresses https://jira.percona.com/browse/PT-2064 which causes PT-archiver to crash when hitting an error. We use pt-archiver to delete rows that shouldn't be moved to another destination, so `--dest` is not provided.

In most places, we seem to check  if `$dst` is actually defined before using it, so we might want to do the same in the `do_with_retries` function?

- [ ] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documention updated
- [ ] Test suite update

2023-03-09 14:27 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=604) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=604) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=604) it.</sub>

2023-04-05 11:42 UTC, svetasmirnova requested changes
Please add a regression test. You will find examples in the t directory and user manual in the contribution guide.

2023-11-06 16:36 UTC, svetasmirnova approved these changes

2023-11-12 19:15 UTC, EvgeniyPatlan approved these changes

2023-11-12 20:28 UTC, merged