Fix An error occurred when I migrated...
percona/percona-toolkit pull request #614
Opened 2023-04-14 09:55 UTC by hanzhongzi

HI, i am back. from issue #605, could this modification is correct?
An error occurred when I migrated data from MySQL to OceanBase:【 DBD::mysql::db do failed: You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near ':= @OLD_SQL_MODE, @@SQL_QUOTE_SHOW_CREATE := @OLD_QUOTE /' at line 1 [for Statement "/!40101 SET @@SQL_MODE := @OLD_SQL_MODE, @@SQL_QUOTE_SHOW_CREATE := @OLD_QUOTE */"] at /usr/bin/pt-archiver line 1932.】

I'm not a Perl programmer. But by reading the source code and making some changes, the migration was done successfully, so I submit this report

- [x] The contributed code is licensed under GPL v2.0
- [x] Contributor Licence Agreement (CLA) is signed
- [x] util/update-modules has been ran
- [x] Not involved Documention updated
- [x] Not involved Test suite update

2023-04-17 12:40 UTC, svetasmirnova approved these changes

2023-04-17 12:50 UTC, percona-csalguero requested changes
Hi, 
Thanks for the patch.
This is actually hiding the error but it is not really fixing it.
Is there any chance of detecting `OceanBase` and run the appropriate command?

2023-06-21 14:01 UTC, svetasmirnova commented
@percona-csalguero this is actually how it is handled few lines earlier. So we either should change our old code or accept this contribution. See

`1895 sub get_create_table {
1896    my ( $self, $dbh, $db, $tbl ) = @_;
1897    die "I need a dbh parameter" unless $dbh;
1898    die "I need a db parameter"  unless $db;
1899    die "I need a tbl parameter" unless $tbl;
1900    my $q = $self->{Quoter};
1901 
1902    my $new_sql_mode
1903       = q{/*!40101 SET @OLD_SQL_MODE := @@SQL_MODE, }
1904       . q{@@SQL_MODE := '', }
1905       . q{@OLD_QUOTE := @@SQL_QUOTE_SHOW_CREATE, }
1906       . q{@@SQL_QUOTE_SHOW_CREATE := 1 */};
1907 
1908    my $old_sql_mode
1909       = q{/*!40101 SET @@SQL_MODE := @OLD_SQL_MODE, }
1910       . q{@@SQL_QUOTE_SHOW_CREATE := @OLD_QUOTE */};
1911 
1912    PTDEBUG && _d($new_sql_mode);
1913    eval { $dbh->do($new_sql_mode); };
1914    PTDEBUG && $EVAL_ERROR && _d($EVAL_ERROR);
`

2023-06-26 11:53 UTC, EvgeniyPatlan approved these changes

2023-06-26 11:54 UTC, merged