PT-2169 - pt-k8s-debug-collector integration of pg_gather requires croping first line of the output file
percona/percona-toolkit pull request #615
Opened 2023-04-15 00:16 UTC by svetasmirnova

Modified pt-k8s-debug-collector so it redirects only STDOUT to summary.txt STDERR is stored in the logs and recorded in summary.txt only if summary fails with the error Modified Makefile, so it does not include closing bracket into the version string Created test case for the fix

- [ ] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documentation updated
- [ ] Test suite update

2023-04-18 12:18 UTC, percona-csalguero approved these changes

2023-04-18 12:50 UTC, egegunes requested changes

2023-04-18 12:50 UTC, egegunes commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +		return outb.Bytes(), nil
this else is not needed, you can just `return outb.Bytes(), nil`

2023-04-19 20:11 UTC, egegunes approved these changes

2023-04-20 00:12 UTC, merged