PT-2211 This pstack return error code line number
percona/percona-toolkit pull request #628
Opened 2023-06-02 12:05 UTC by baotiao

[PT-2211 This pstack return error code line number](https://github.com/percona/percona-toolkit/commit/b6626a5784b746e8e133ba2330488d73b9fd7066)

2023-06-02 12:05 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=628) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=628) before we can accept your contribution.<br/><hr/>**zongzhi.czz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=628) it.</sub>

2023-07-28 11:35 UTC, svetasmirnova requested changes
Could you please add a test case? You will find examples in the contribution guide and in the directory t/pt-pmp

2023-11-02 23:48 UTC, svetasmirnova commented
OK, added test samples myself.

2023-11-02 23:48 UTC, svetasmirnova approved these changes

2023-11-12 19:15 UTC, EvgeniyPatlan approved these changes

2023-11-12 20:27 UTC, merged