PT-2232 Release Notes 3.5.4
percona/percona-toolkit pull request #633
Opened 2023-06-22 10:05 UTC by alina-derkach-oaza

modified:   Changelog
	modified:   Makefile.PL
	modified:   config/sphinx-build/conf.py
	modified:   docs/release_notes.rst

- [ ] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documention updated
- [ ] Test suite update

2023-06-22 10:22 UTC, patrickbirch approved these changes
LGTM

2023-06-26 11:58 UTC, svetasmirnova commented on Changelog
> +* Improvement PT-2151: Fix tests for pt-query-digest
```suggestion
* Improvement PT-2151: Fix tests for pt-query-digest
* Improvement PR-617:   Remove $has_child_tables var (Thanks to Ricardo for the contribution)
```

2023-06-26 12:03 UTC, svetasmirnova commented on Changelog
> +* Fixed bug PT-2229: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue)
```suggestion
* Fixed bug PT-2229: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue and testing the fix)
```

2023-06-26 12:09 UTC, svetasmirnova commented on docs/release_notes.rst
> +* :jirabug:`PT-2229`: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue)
```suggestion
* :jirabug:`PT-2229`: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue and testing the fix)
```

2023-06-26 12:10 UTC, svetasmirnova commented on docs/release_notes.rst
> +* :jirabug:`PT-981`: LP #1008240: t/pt-query-digest/processlist.t occasionally fails
```suggestion
* :jirabug:`PT-981`:  LP #1008240: t/pt-query-digest/processlist.t occasionally fails
```

2023-06-26 12:11 UTC, svetasmirnova requested changes
Please review the changes I suggested.

2023-06-26 14:52 UTC, alina-derkach-oaza commented on Changelog
> +* Improvement PT-2151: Fix tests for pt-query-digest
done

2023-06-26 14:52 UTC, alina-derkach-oaza commented on docs/release_notes.rst
> +* :jirabug:`PT-2229`: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue)
done

2023-06-26 14:53 UTC, alina-derkach-oaza commented on docs/release_notes.rst
> +* :jirabug:`PT-981`: LP #1008240: t/pt-query-digest/processlist.t occasionally fails
done

2023-06-26 14:53 UTC, alina-derkach-oaza commented on Changelog
> +* Fixed bug PT-2229: CVE reported in Percona Toolkit version 3.5.3 related to Logrus (Thanks to Kushal Haldar for reporting this issue)
done

2023-06-26 15:26 UTC, svetasmirnova approved these changes

2023-06-26 15:26 UTC, merged