War on typos Act 1
percona/percona-toolkit pull request #655
Opened 2023-08-05 15:45 UTC by szepeviktor

- [x] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documention updated
- [ ] Test suite update

Hello!
Fixed typos in `bin/` with a tool called `typos`.
There may be collateral damage. Please review.

After this one gets merged I proceed with other directories 🚀

2023-08-05 15:45 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=655) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=655) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=655) it.</sub>

2023-08-05 15:48 UTC, szepeviktor commented
🎈 Fun fact: "arugment" is the TOP typo.

2023-08-05 16:59 UTC, szepeviktor commented
At the end `typos` could be in a CI workflow!

2023-08-09 19:02 UTC, szepeviktor commented
@svetasmirnova Friendly ping 🏓

2023-08-16 12:14 UTC, svetasmirnova requested changes
You changed only tools code while Percona Toolkit auto-generates most of the tool code from modules. As a result, all your work will be wiped after we run the update-modules script. Please take a look at Contributing guide for details. Please move your changes to the proper places.

2023-08-16 12:36 UTC, szepeviktor commented
Thank you Света!
I thought the opposite, left lib/* files alone :)

Fixing ... 🏃🏻‍♂️

2023-08-16 13:01 UTC, szepeviktor commented
@svetasmirnova Done 🍏
I've put typo fixes and generated files in separate commits for you.

2023-08-16 13:02 UTC, szepeviktor commented on lib/RowChecksum.pm
> +   PTDEBUG && _d('Checksum start:', Dumper(\%crc_args));
I am unsure here.

2023-08-16 21:45 UTC, svetasmirnova commented on lib/RowChecksum.pm
> +   PTDEBUG && _d('Checksum start:', Dumper(\%crc_args));
Should be OK

2023-08-17 14:15 UTC, svetasmirnova commented
Thank you! I added some changes, so tests are now passed.

2023-08-17 14:15 UTC, svetasmirnova approved these changes

2023-08-17 14:28 UTC, szepeviktor commented
Thank you for your commit!

I was looking for an `update-everything-everywhere.sh` script but could not find it.
Contributors may find it useful.

2023-08-22 13:17 UTC, EvgeniyPatlan approved these changes

2023-08-22 13:18 UTC, merged