Pt 2247
percona/percona-toolkit pull request #686
Opened 2023-09-24 15:54 UTC by Tusamarco

- [ x] The contributed code is licensed under GPL v2.0
- [ x] Contributor Licence Agreement (CLA) is signed
- [ NA] util/update-modules has been ran
- [ x] Documentation updated
- [NA ] Test suite update

@svetasmirnova please check and review also https://jira.percona.com/browse/PT-2247

2023-10-06 11:13 UTC, svetasmirnova requested changes
PLease add test case. You can find how in the contribution guide and examples in t/pt-show-grants/

2023-10-06 11:14 UTC, svetasmirnova requested changes

2023-10-06 11:14 UTC, svetasmirnova commented on bin/pt-show-grants
> +      if (( VersionCompare::cmp($version, '5.7.6') >= 0 ) ||
With "||" this expression is always true.

2023-10-06 11:19 UTC, svetasmirnova commented on bin/pt-show-grants
> +When set it convert some of the proprietary MariaDB syntax into valid MySQL form
Can't we do this automatically if we connect to MariaDB? Or will it break for valid MySQL syntax?

2023-11-02 22:57 UTC, svetasmirnova commented on bin/pt-show-grants
> +=item --print_identified_with_as_hex
According to the user manual at https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_print_identified_with_as_hex:

> Hash values that do not contain unprintable characters still display as regular string literals, even with this variable enabled. 

Do we really need this option or checking for correct MySQL version is enough?

2024-05-16 22:44 UTC, svetasmirnova commented on bin/pt-show-grants
> +When set it convert some of the proprietary MariaDB syntax into valid MySQL form
Looks like not, useful option.

2024-05-16 23:37 UTC, svetasmirnova commented
@Tusamarco I changed your PR: simplified a few things, removed the option --print_identified_with_hex (made it default and only behavior), and added a test case. Please review and see if you agree with the changes.

2024-05-20 15:44 UTC, Tusamarco reviewed
LGTM

2024-05-20 15:49 UTC, svetasmirnova approved these changes

2024-05-21 14:29 UTC, EvgeniyPatlan approved these changes

2024-05-21 14:30 UTC, merged