Follow PR-429 unstop option with testcase
percona/percona-toolkit pull request #706
Opened 2023-11-07 13:26 UTC by svetasmirnova

- [ ] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documentation updated
- [ ] Test suite update

2023-11-12 19:11 UTC, EvgeniyPatlan requested changes

2023-11-12 19:11 UTC, EvgeniyPatlan commented on bin/pt-archiver
> +         or die "Cannot unlink sentinel file: $OS_ERROR\n";
I would suggest 
"Cannot unlink $sentinel file: $OS_ERROR\n";

2023-11-23 08:44 UTC, EvgeniyPatlan approved these changes

2023-12-04 07:59 UTC, saikumar-vs approved these changes

2023-12-04 10:10 UTC, merged