PT-2299 - collect openssl x509 certificate information for each secret
percona/percona-toolkit pull request #816
Opened 2024-05-13 22:57 UTC by svetasmirnova

- Implemented the feature
- Added test case

- [ ] The contributed code is licensed under GPL v2.0
- [ ] Contributor Licence Agreement (CLA) is signed
- [ ] util/update-modules has been ran
- [ ] Documentation updated
- [ ] Test suite update

2024-05-15 16:10 UTC, artemgavrilov approved these changes
LGTM with comment

2024-05-15 16:10 UTC, artemgavrilov commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +	"html/template"
Most likely you want here `text/template`

2024-05-15 16:20 UTC, ihanick commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +	switch resource {
it should be a`switch resourceType(resource)`.
with plain `switch resource`, it's not working (and breaks pxc) the new code breaks
`pt-k8s-debug-collector -cluster cluster1 -namespace pgo -resource pgv2`
the dumper receives pgv2/cluster1 string inside resource variable.

2024-05-15 16:21 UTC, ihanick requested changes
not working if -cluster argument is specified, instead of switch resource it should be switch resourceType(resource)

2024-05-15 19:27 UTC, ihanick commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +	"html/template"
I've tried text/template and it works as expected

2024-05-15 19:28 UTC, ihanick commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +		)
another two are required
+                       sslSecret{
+                               secret:    "{{ .Name }}-ssl-keypair",
+                               resource:  "perconapgclusters",
+                               dataNames: []string{"tls.crt"},
+                       },
+                       sslSecret{
+                               secret:    "{{ .Name }}-replication-ssl-keypair",
+                               resource:  "perconapgclusters",
+                               dataNames: []string{"tls.crt"},
+                       },

2024-05-15 19:32 UTC, ihanick commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +				resource:  "perconapgclusters",
here and in https://github.com/percona/percona-toolkit/blob/9b3d92997a32395c7082b5990e363275c60c1711/src/go/pt-k8s-debug-collector/dumper/dumper.go#L85 it's better to use a resource type name with percona's domain. If another operator with same short name is installed (or v1 and v2 ) it causes conflicts
```
-                       "perconapgclusters",
-                       "pgclusters",
-                       "pgpolicies",
-                       "pgreplicas",
-                       "pgtasks",
+                       "perconapgclusters.pg.percona.com",
+                       "pgclusters.pg.percona.com",
+                       "pgpolicies.pg.percona.com",
+                       "pgreplicas.pg.percona.com",
+                       "pgtasks.pg.percona.com",
                )
        case "pgv2":
                resources = append(resources,
-                       "perconapgbackups",
-                       "perconapgclusters",
-                       "perconapgrestores",
+                       "perconapgbackups.pgv2.percona.com",
+                       "perconapgclusters.pgv2.percona.com",
+                       "perconapgrestores.pgv2.percona.com",
```

2024-05-15 19:34 UTC, ihanick requested changes
please fix comments related to text/template, add missing certificates for pg v1, potentially update the resource name to the full one. for v1, the secret name could be changed

2024-05-15 22:43 UTC, svetasmirnova commented
> not working if -cluster argument is specified, instead of switch resource it should be switch resourceType(resource)

This is a known issue: https://perconadev.atlassian.net/browse/PT-2189

2024-05-21 15:02 UTC, svetasmirnova commented on src/go/pt-k8s-debug-collector/dumper/dumper.go
> +			".perconapgbackups.pgv2.percona.com",
```suggestion
			"perconapgbackups.pgv2.percona.com",
```

2024-05-21 21:34 UTC, ihanick approved these changes
LGTM

2024-05-21 21:37 UTC, merged