fix: Allow proper filtering with --where in parent-child relationships
percona/percona-toolkit pull request #885
Opened 2024-11-11 16:24 UTC by antoniocunh

Problem Description:

When using the --where filter in pt-online-schema-change, an error occurs when the filter is applied to a parent table (e.g., city), and the tool attempts to propagate changes to related child tables (e.g., address). Specifically, the --where condition is applied to the parent table, but the tool erroneously tries to apply this filter to child tables that do not contain the referenced column. This causes an error, as the columns in the child tables do not exist, leading to a failure during the operation.

The issue arises because pt-online-schema-change tries to apply the filter to the child tables, where the column being referenced in the --where condition (e.g., status in city) does not exist. This behavior prevents the tool from successfully executing the change and results in the error, particularly in relationships with foreign keys between the tables.

Example SQL:
```
CREATE TABLE `city` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `city` varchar(50) NOT NULL,
  `country_id` smallint(5) unsigned NOT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),  -- corrected from `city_id` to `id`
  KEY `idx_fk_country_id` (`country_id`),
  CONSTRAINT `fk_city_country` FOREIGN KEY (`country_id`) REFERENCES `country` (`country_id`) ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `address` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `address` varchar(50) NOT NULL,
  `city_id` smallint(5) unsigned NOT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),  -- corrected from `address_id` to `id`
  KEY `idx_fk_city_id` (`city_id`),
  CONSTRAINT `fk_address_city` FOREIGN KEY (`city_id`) REFERENCES `city` (`id`) ON UPDATE CASCADE  -- corrected to reference `id` in `city`
) ENGINE=InnoDB;
```

In this example, the tables city and address are related via a foreign key (city_id in address referencing id in city). If a --where filter is applied to the city table, pt-online-schema-change might incorrectly attempt to apply this filter to the address table as well, causing an error because the status column (referenced in the --where condition) does not exist in the child table.

Note: Unfortunately, I was unable to run the tests locally, so I have not included any test commits with this pull request. If this issue doesn't seem relevant, could you please provide guidance on resolving this locally so that I can run the tests correctly?

- [x] The contributed code is licensed under GPL v2.0
- [x] Contributor Licence Agreement (CLA) is signed
- [x] util/update-modules has been ran
- [ ] Documentation updated
- [ ] Test suite update

2024-11-11 16:24 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=885) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=885) before we can accept your contribution.<br/><hr/>**António Cunha** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=885) it.</sub>

2024-11-13 14:06 UTC, svetasmirnova requested changes
Please add a test case.

2024-11-18 11:17 UTC, antoniocunh commented
I would appreciate it if you could run the CI to confirm that everything is working correctly. :)

2024-12-25 13:40 UTC, svetasmirnova commented
@antoniocunh 

Thank you for the update. There are instructions how to run tests in CONTRIBUTING.md I myself run following snippet:
```
export PERCONA_TOOLKIT_SANDBOX=$HOME/mysqlpackages/Percona-Server-8.0.39-30-Linux.x86_64.glibc2.35
export PERCONA_TOOLKIT_BRANCH=`pwd`
export BRANCH=$(git rev-parse --abbrev-ref HEAD)
export MYSQL_VERSION=8.0
export LOG_FILE=~/${BRANCH}-${MYSQL_VERSION}.log
sandbox/test-env restart
prove -vr --trap --timer t/pt-online-schema-change/pt-1751.t
```

2024-12-25 13:52 UTC, svetasmirnova requested changes
In my case, test fails when tries to load t/pt-online-schema-change/samples/basic_with_fks_diff_ids.sql:

```
$ ptmaster < t/pt-online-schema-change/samples/basic_with_fks_diff_ids.sql
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 45: Unknown column 'city_id' in 'field list'
```
Please correct this SQL file.

2026-09-01 18:45 UTC, closed without merging