pt-config-diff: MySQL truncates run-time variable values longer than 1024 characters
percona/percona-toolkit pull request #890
Opened 2024-12-04 07:36 UTC by dbnski

`pt-config-diff` relies on `SHOW GLOBAL VARIABLES` for listing run-time variables. MySQL 5.7 and newer implement the command by reading the contents of the `performance_schema` table called `global_variables`, but the table definition uses `VARCHAR(1024)` for the value field. Any value longer than 1024 characters becomes truncated both in the table as well as in the `SHOW GLOBAL VARIABLES` command output. This makes comparing long run-time variables unreliable. The patch works around the problem by reading full values from the `@@global` object whenever necessary.

2024-12-04 07:36 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=890) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=890) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=890) it.</sub>

2024-12-25 13:31 UTC, svetasmirnova requested changes
You modified auto-generated code. Please place your changes into lib/MySQLConfig.pm, then run ./util/update-modules command.

Please also add a test case. You will find examples in t/lib/MySQLConfig.t and in t/pt-config-diff/

2025-06-06 18:42 UTC, dbnski commented
Updated MySQLConfig.pm and added test cases.

2025-06-12 23:35 UTC, svetasmirnova commented
Thank you for the patch update and the test case. I modified the test variable so it works with versions 5.7, 8.0, and 8.4. Please review and let me know if it is OK to remove long_vars_57_1.cnf, long_vars_57_2.cnf, long_vars_80_1.cnf, long_vars_80_2.cnf samples.

2025-06-20 08:21 UTC, EvgeniyPatlan approved these changes

2025-06-20 09:46 UTC, dbnski commented
@svetasmirnova Sure, that is great. I was looking for a var that'd work across all versions, but didn't catch that one.

2025-06-22 12:49 UTC, svetasmirnova approved these changes

2025-06-22 12:53 UTC, merged