PT-2401 - remove check to fix the 'table does not exist' problem when lower_case_table_names=2 is set
percona/percona-toolkit pull request #891
Opened 2024-12-06 09:29 UTC by ehooi

pt-online-schema-change failed with 'table `TableName` does not exist', but the table exists.

It seems that #516 introduces this issue.

The variable $tbl changed to lowercase as `tablename` but MySQL returned the original case `TableName` when `lower_case_table_names=2` is set.
As a result, the check that I removed fails.

Since the check appeared to be primarily preventive, I decided to remove it.

2024-12-06 09:29 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=891) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-toolkit?pullRequest=891) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-toolkit?pullRequest=891) it.</sub>

2024-12-25 13:26 UTC, svetasmirnova requested changes
Please add a test case. You can take t/pt-online-schema-change/case-insensitive.t as example.

2025-08-15 14:19 UTC, svetasmirnova approved these changes

2025-08-15 14:20 UTC, svetasmirnova commented
I modified the code so it still checks the table name but now takes into account the value of the lower_case_table_names option. I hope this is OK for you. Regarding the test case, I think t/pt-online-schema-change/case-insensitive.t is enough because we cannot modify this test to check the lower_case_table_names option on Linux anyway.

2025-08-26 07:30 UTC, EvgeniyPatlan approved these changes

2025-08-26 16:44 UTC, merged