PT-2410 - Fixing the export with output-format=csv when there are null values
percona/percona-toolkit pull request #903
Opened 2024-12-21 18:03 UTC by Robertoh98

Fixing the bug reported at https://perconadev.atlassian.net/browse/PT-2410.

I added to the if on the escape function the \N to be escaped from the enclosed by ".

2024-12-23 11:41 UTC, svetasmirnova commented
Thank you for the fix. Please add a test case for your fix.

2024-12-23 11:42 UTC, svetasmirnova requested changes
Please add a test case. You will find examples in directory t/pt-archiver

2025-03-13 19:58 UTC, svetasmirnova approved these changes

2025-03-14 08:04 UTC, EvgeniyPatlan approved these changes

2025-03-18 12:02 UTC, merged